### ISSUE TITLE
[Bug]: Inaccessible Generated Images from API (Behind a Load Balancer + API Key)

### ISSUE THREAD

**Issue by ldavis9000aws** [mrhan1993/FooocusAPI#20]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Generated image URLs include a port number, causing them to fail when accessed behind a load balancer that exposes only ports 80 and 443. Removing the port number from the URL results in a 403 Forbidden error due to the requirement of a custom x-api-key header. Disabling the API key option allows image access without the port number.

![image](https://github.com/mrhan1993/FooocusAPI/assets/42821964/ea42fe6c-d714-4d35-a37c-199d5270859a)

### Steps to reproduce the problem

1. Start the API using the following command:
`python launch.py --listen 0.0.0.0 --port 8888 --base-url fooocusapi.your-url.com --apikey %fooocus-apikey% --debug-mode --nowebui`

2. Generate an image using the API.
3. Attempt to access the generated image URL with the port number behind a load balancer (ports 80 and 443).
4. Remove the port number from the URL and attempt to access the image.

### What should have happened?

Direct access to the generated image via URL without requiring a port number or custom header.

### What browsers do you use to access Fooocus?

Google Chrome, Microsoft Edge

### Where are you running Fooocus?

Cloud (other)

### Console logs

```Shell
INFO:     10.0.13.1:41688 - "GET /outputs/2024-07-11/2024-07-11_18-57-43_5837.png HTTP/1.1" 403 Forbidden
INFO:     127.0.0.1:52007 - "GET /outputs/2024-07-11/2024-07-11_18-57-43_5837.png HTTP/1.1" 403 Forbidden
```

### Additional information

What I'd like to see:

**Remove the Port Number from Image URLs:**
Ensure the FastAPI backend generates image URLs without including the port number, to maintain compatibility with load balancers exposing only ports 80 and 443.

**Allow Image Retrieval without API Key:**
Adjust the FastAPI configuration to allow public access to image retrieval endpoints without requiring the x-api-key header, while maintaining API key protection for all other operations.

I'd like the URL retrieval to work like it did originally by only requiring API keys for all other endpoints except the retrieval of images. This will keep the API operations secure while allowing easier access for users.

**Comment by mrhan1993** [comment]
An update will be soon

**Comment by mrhan1993** [comment]
An update has pushed, I removed auth for output, and you can by pass API_PORT to specify the api port
