### ISSUE TITLE
Instaling on Ubuntu 24.04

### ISSUE THREAD

**Issue by tux-** [mrhan1993/FooocusAPI#21]
### Checklist

- [X] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Installing on Ubuntu 24.04 gives errors when running `pip install -r requirements_versions.txt`

### Steps to reproduce the problem

git clone https://github.com/mrhan1993/FooocusAPI.git
cd FooocusAPI
python3 -m venv fooocus_env
source fooocus_env/bin/activate
pip install -r requirements_versions.txt

### What should have happened?

Should install.

### Where are you running Fooocus?

Locally

### What operating system are you using?

Ubuntu 24.04

### Console logs

```Shell
Collecting pyyaml==6.0 (from -r requirements_versions.txt (line 6))
  Using cached PyYAML-6.0.tar.gz (124 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
```

### Additional information

Modifying the file to have this contents, and it works:

```
torchsde
einops
transformers
safetensors
accelerate
pyyaml
Pillow
scipy
tqdm
psutil
pytorch_lightning
omegaconf
gradio==3.41.2
pygit2
opencv-contrib-python
onnxruntime
timm
sse_starlette
sqlalchemy
httpx
```

**Comment by mrhan1993** [comment]
Since your output contains `Using cached PyYAML-6.0.tar.gz`, I suggest you execute `pip cache purge` first and try again

![图片](https://github.com/user-attachments/assets/f61c6e3e-7385-49a5-bff9-ed6f4e879b3f)

**Comment by tux-** [comment]
In the current main branch requirements_versions.txt it does say to use PyYAML-6.0. If I change just that one to say PyYAML-6.0.1 and try, new bugs appear. This is in fresh install of Ubuntu 24.04. Tried it on two different VM's and it is exactly same problem. After `pip cache purge` problem persists as well.

**Comment by mrhan1993** [comment]
Sorry, my fault. I tested in 22.04. I will check it now

**Comment by mrhan1993** [comment]
I'm sure this issue is caused by the version of Python, and the default Python version for Ubuntu 24.04 is 3.12.
I would recommend that you use Python 3.10 as the running environment for the Fooocus API, or you can follow the requirements you mentioned above to remove the version number, but this has not been fully tested. In order to be consistent with Fooocus, it will not be merged into the mainline.

**Comment by tux-** [comment]
Yeah, looks like Fooocus has the same issue. I have no clue how to install different Python versions. How ever, I do know that using the above posted txt file, make it all run without issues. So, I guess this is more like a guide on how to make it work out of the box on Ubuntu 24.04. Maybe it should have been a wiki post instead or something, not sure if you want to enable wiki tho.
