### ISSUE TITLE
[Feature Request]: date_string in filename optional

### ISSUE THREAD

**Issue by kickin6** [mrhan1993/FooocusAPI#29]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

Make the `date_string` in the `filename` optional.

https://github.com/mrhan1993/FooocusAPI/blob/2c19778064a36848cd5309894fcd4076c6c7b249/apis/utils/file_utils.py#L76-L69

My use case:
I need to group output files by customer api-key `/outputs/images/{api-key}/files...` which makes it easier to put a front-end to list their files without having to scan all `/outputs/date_string/{api-key}/` directories.

In my frontend app, after api-key validation, I set the `save_name` parameter to the api_key:
```
data["save_name"] = f"images/{api_key}"
```

### Proposed workflow

I propose a new environment variable `os.environ["FILENAME_WITH_DATE"]` or similar.

```python
date_string = current_time.strftime("%Y-%m-%d") if os.environ["FILENAME_WITH_DATE"] else ""
filename = os.path.join(date_string, f"{image_name}.{extension}")
```

**Comment by mrhan1993** [comment]
I know what you need, but function `save_output_file`  is useless.  save output is [here](https://github.com/mrhan1993/FooocusAPI/blob/2c19778064a36848cd5309894fcd4076c6c7b249/modules/async_worker.py#L1006), and function is [here](https://github.com/mrhan1993/FooocusAPI/blob/2c19778064a36848cd5309894fcd4076c6c7b249/modules/private_logger.py#L24).  I do not want modify the code of Fooocus, so i change file name after generate finish [here](https://github.com/mrhan1993/FooocusAPI/blob/161f161d7d909ef303b93c879aa780ea4f20ff85/apis/utils/file_utils.py#L226), I can meet your needs, but I'm still designing a more reasonable way.

**Comment by mrhan1993** [comment]
I pushed a commit in v2.5 branch, you can set `save_name='../{api-key}/filename'`, it will return `http://127.0.0.1:7866/outputs/{api-key}/filename-{seq}.{output_format}`, seq is used for multi image in one generate, from 0.

**Comment by kickin6** [comment]
Thanks!
