### ISSUE TITLE
[Bug]: params.extend(req.save_final_enhanced_image_only) TypeError: 'bool' object is not iterable

### ISSUE THREAD

**Issue by prog-ape** [mrhan1993/FooocusAPI#41]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

File "/home/ai/FooocusAPI/apis/utils/api_utils.py", line 104, in params_to_params
    params.extend(req.save_final_enhanced_image_only)
TypeError: 'bool' object is not iterable

### Steps to reproduce the problem

File "/home/ai/FooocusAPI/apis/utils/api_utils.py", line 104, in params_to_params
    params.extend(req.save_final_enhanced_image_only)
TypeError: 'bool' object is not iterable

### What should have happened?

Passing the save_final_enhanced_image_only parameter still results in an exception

### Where are you running Fooocus?

None

### What operating system are you using?

ubuntu

### Console logs

```Shell
File "/home/ai/FooocusAPI/apis/utils/api_utils.py", line 104, in params_to_params
    params.extend(req.save_final_enhanced_image_only)
TypeError: 'bool' object is not iterable
```

**Comment by mrhan1993** [comment]
sorry，fixed it
